CREATE OR ALTER VIEW VW_SHOW_AVAILABLE_MOVIES AS
SELECT * FROM dbo.FILME
WHERE STATUS = 'Disponível' AND RESERVADA = 'N';

SELECT * FROM VW_SHOW_AVAILABLE_MOVIES;

CREATE OR ALTER VIEW VW_MOST_RENTED_MOVIES AS
SELECT F.COD_FILME, F.FILME, COUNT(L.COD_FILME) AS TOTAL_LOCACOES
FROM dbo.LOCACOES L JOIN dbo.FILME F ON F.COD_FILME = L.COD_FILME
GROUP BY F.COD_FILME, F.FILME;

SELECT * FROM VW_MOST_RENTED_MOVIES ORDER BY TOTAL_LOCACOES DESC;